name: webhook_test
description: A Dart server to handle webhooks
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.1
  json_annotation: ^4.9.0
  shelf_router: ^1.1.4
  http: ^1.2.2
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  test: ^1.25.7
